version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: phonebook-postgres
    environment:
      POSTGRES_DB: PhonebookDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - phonebook-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: phonebook-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - phonebook-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Contact Service API
  contact-service:
    build:
      context: .
      dockerfile: ContactServiceAPI/Dockerfile
    container_name: phonebook-contact-api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=PhonebookDb;Username=postgres;Password=postgres
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=user
      - RabbitMQ__Password=password
      - RabbitMQ__Port=5672
    ports:
      - "8081:8080"
    networks:
      - phonebook-network

  # Report Service API
  report-service:
    build:
      context: .
      dockerfile: ReportServiceAPI/Dockerfile
    container_name: phonebook-report-api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=PhonebookDb;Username=postgres;Password=postgres
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=user
      - RabbitMQ__Password=password
      - RabbitMQ__Port=5672
    ports:
      - "8082:8080"
    networks:
      - phonebook-network
    restart: unless-stopped

networks:
  phonebook-network:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data: 