name: .NET Tests

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Generate test coverage report
      run: dotnet test --no-build --collect:"XPlat Code Coverage"
      
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: "**/TestResults/**/*.xml" 